In [1]:
import pandas as pd
import numpy as np

import os

In [2]:
lines = pd.read_csv(
    "movie-conversation/movie_lines.tsv", 
    encoding='utf-8-sig', 
    sep='\t', 
    on_bad_lines="skip", 
    header = None,
    names = ['lineID', 'charID', 'movieID', 'charName', 'text'],
    index_col=['lineID']
)

In [3]:
lines

,charID,movieID,charName,text
lineID,,,,
L1045,u0,m0,BIANCA,They do not!
L1044,u2,m0,CAMERON,They do to!
L985,u0,m0,BIANCA,I hope so.
L984,u2,m0,CAMERON,She okay?
L925,u0,m0,BIANCA,Let's go.
...,...,...,...,...
L666371,u9030,m616,DURNFORD,Lord Chelmsford seems to want me to stay back ...
L666370,u9034,m616,VEREKER,I'm to take the Sikali with the main column to...
L666369,u9030,m616,DURNFORD,Your orders Mr Vereker?
L666257,u9030,m616,DURNFORD,Good ones yes Mr Vereker. Gentlemen who can ri...
L666256,u9034,m616,VEREKER,Colonel Durnford... William Vereker. I hear yo...

In [4]:
data = {}

for d in lines.itertuples():
    if type(d[4]) != type(''):
        continue

    words = list(filter(lambda x: x != '', d[4].split(' ')))
    name = d[1].lower()
    try:
        data[name] += words
    except:
        data.__setitem__(name, words)

In [5]:
df = pd.DataFrame({
    'character': list(data.keys()),
    'words': data.values() 
})

In [6]:
df.to_csv('movie-conversation.csv', index=False)